### ISSUE TITLE
백준 10989번 문제

### ISSUE THREAD

**Issue by kpeel5839** [kpeel5839/Algorithm_tutoring#2]
## 10989 (Counting Sort , https://www.acmicpc.net/problem/10989)
- - [x] 수연
- - [x] 연주
- - [x] 지윤
- - [x] 자경

문제 풀고 올려주세요~
## `java project 이름은 10989_problem 으로 해주세요`

**Comment by dd-jiyun** [comment]
넹

**Comment by kpeel5839** [comment]
> 넹

감사합니다
